### ISSUE TITLE
Config not properly persisted

### ISSUE THREAD

**Issue by stevegroom** [aws-samples/aws-media-asset-preparation-system#5] opened 2021-03-07 18:21 UTC
After installing and testing MAP using Chrome

* Open URL
* Login
* Connect to S3 bucket
* View and manipulate files successfully

 I later tried it out using Edge. 

* Open URL
* Login
* No files or folders are visible - no S3 bucket is configured 

The issue seems to be that the configuration is stored in a browser cookie and not centrally.

**Comment by kwwendt** [comment] 2021-03-08 19:21
Thank you for the feedback! This is by design to give users more freedom to easily switch between different buckets. However, it is feedback I've received from other users and implementing centrally managed settings is on my radar.

**Comment by stevegroom** [comment] 2021-03-09 09:24
Thank you for the feedback. Supporting multiple S3 buckets would also be very helpful - when we have regional assets needing local performance and also for moving assets between different storage classes.

**Comment by kwwendt** [comment] 2021-04-01 18:10
Hi Steve! Wanted to let you know I just merged in a feature that will persist the bucket configuration for the MAPS deployment.

For supporting multiple buckets, can you open a separate issue for this so we can track it?
Similarly, can you open a separate issue for moving assets between storage classes?

Thanks!

**Closed by kwwendt** 2021-04-01 18:10 UTC
Labels: enhancement
